[package]
authors = ["Sylvain Wallez <sylvain@bluxte.net>"]
edition = "2018"
name = "gdocs2hugo"
version = "0.1.0"

[dependencies]
# Base stuff
anyhow = "1.0.32"
chrono = { version = "0.4.15", features = ["serde"] }
indoc = "1.0.2"
lazy_static = "1.4.0"
maplit = "1.0.2"
regex = "1.3.9"
structopt = "0.3.18"
rayon = "1.4.1"

# Serde and formats
serde = {version = "1.0.114" }
serde_derive = {version = "1.0.114" }
csv = "1.1.3"
serde_yaml = "0.8.13"

# HTML and CSS parsing
html5ever = "0.25.1"
cssparser = "0.27.2"

scraper = "0.12.0"
ego-tree = "*"
tendril = "*"
markup5ever = "*"

# HTTP
reqwest = {version = "0.10.7", features = ["blocking"] }
bytes = "*"
mime_guess = "2.0.3"

# Used for images
image = "0.23.10"
globwalk = "0.8.0"
